language: scala
scala:
  - 2.12.4

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    - kamilduda01@gmail.com

branches:
  only:
    - master
    - develop
    - stable

env:
  - ENVIRONMENT=ci

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test &&
    sbt coverageReport &&
    sbt coverageAggregate &&
    sbt codacyCoverage
    sbt dist

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: "target/universal/play-hateoas-0.1-SNAPSHOT.zip"
  skip_cleanup: true
  on:
    tags: true